version: "3.9"
services:

  pong:
    build:
      dockerfile: ../../svcs/pong/Dockerfile
      context: ../dist/pong
    init: true
    depends_on:
      - mongodb
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ../dist/pong/src:/home/node/app/src
      - ../.yarn:/home/node/.yarn
    command: "yarn nodemon src/index.mjs"

  mongodb:
    image: "mongo:${MONGO_VERSION}"
    restart: always
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - mongodb_volume:/data/db
    command: mongod --quiet --logpath /dev/null

volumes:
  mongodb_volume:
